services:
  mongo:
    image: mongo:7
    container_name: staygo-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: stayandgo
    volumes:
      - staygo_mongo_data:/data/db

volumes:
  staygo_mongo_data:
