const mongoose = require('mongoose');

// ── Student profiles (10 students: 5 male, 5 female) ──
const studentIds = Array.from({ length: 10 }, () => new mongoose.Types.ObjectId());

const students = [
    {
        _id: studentIds[0],
        firstName: 'Ashan',
        lastName: 'Perera',
        address: '45 Galle Road, Colombo 03',
        email: 'ashan.perera@university.lk',
        whatsApp: '+94771234501',
        gender: 'Male',
        age: 21,
        sleepSchedule: 'EARLY_BIRD',
        cleanliness: 4,
        socialHabits: 'MODERATE',
        studyHabits: 'SILENT',
        profileCompleted: true,
        roomPreferenceCompleted: true,
        finalLockCompleted: false,
    },
    {
        _id: studentIds[1],
        firstName: 'Kavindu',
        lastName: 'Silva',
        address: '12 Temple Lane, Kandy',
        email: 'kavindu.silva@university.lk',
        whatsApp: '+94771234502',
        gender: 'Male',
        age: 22,
        sleepSchedule: 'EARLY_BIRD',
        cleanliness: 5,
        socialHabits: 'MODERATE',
        studyHabits: 'SILENT',
        profileCompleted: true,
        roomPreferenceCompleted: true,
        finalLockCompleted: false,
    },
    {
        _id: studentIds[2],
        firstName: 'Nuwan',
        lastName: 'Fernando',
        address: '78 Beach Road, Negombo',
        email: 'nuwan.fernando@university.lk',
        whatsApp: '+94771234503',
        gender: 'Male',
        age: 20,
        sleepSchedule: 'NIGHT_OWL',
        cleanliness: 3,
        socialHabits: 'SOCIAL',
        studyHabits: 'ANY',
        profileCompleted: true,
        roomPreferenceCompleted: true,
        finalLockCompleted: false,
    },
    {
        _id: studentIds[3],
        firstName: 'Tharindu',
        lastName: 'Jayawardena',
        address: '23 Hill Street, Galle',
        email: 'tharindu.j@university.lk',
        whatsApp: '+94771234504',
        gender: 'Male',
        age: 23,
        sleepSchedule: 'NIGHT_OWL',
        cleanliness: 2,
        socialHabits: 'QUIET',
        studyHabits: 'SOME_NOISE',
        profileCompleted: true,
        roomPreferenceCompleted: true,
        finalLockCompleted: false,
    },
    {
        _id: studentIds[4],
        firstName: 'Dinesh',
        lastName: 'Rathnayake',
        address: '56 Lake View, Kurunegala',
        email: 'dinesh.r@university.lk',
        whatsApp: '+94771234505',
        gender: 'Male',
        age: 21,
        sleepSchedule: 'EARLY_BIRD',
        cleanliness: 4,
        socialHabits: 'MODERATE',
        studyHabits: 'SOME_NOISE',
        profileCompleted: true,
        roomPreferenceCompleted: true,
        finalLockCompleted: false,
    },
    {
        _id: studentIds[5],
        firstName: 'Sachini',
        lastName: 'Wijesinghe',
        address: '89 Flower Road, Colombo 07',
        email: 'sachini.w@university.lk',
        whatsApp: '+94771234506',
        gender: 'Female',
        age: 20,
        sleepSchedule: 'EARLY_BIRD',
        cleanliness: 5,
        socialHabits: 'QUIET',
        studyHabits: 'SILENT',
        profileCompleted: true,
        roomPreferenceCompleted: true,
        finalLockCompleted: false,
    },
    {
        _id: studentIds[6],
        firstName: 'Nethmi',
        lastName: 'De Silva',
        address: '34 Park Avenue, Dehiwala',
        email: 'nethmi.ds@university.lk',
        whatsApp: '+94771234507',
        gender: 'Female',
        age: 21,
        sleepSchedule: 'EARLY_BIRD',
        cleanliness: 4,
        socialHabits: 'MODERATE',
        studyHabits: 'SILENT',
        profileCompleted: true,
        roomPreferenceCompleted: true,
        finalLockCompleted: false,
    },
    {
        _id: studentIds[7],
        firstName: 'Hansi',
        lastName: 'Kumari',
        address: '67 Main Street, Matara',
        email: 'hansi.k@university.lk',
        whatsApp: '+94771234508',
        gender: 'Female',
        age: 22,
        sleepSchedule: 'NIGHT_OWL',
        cleanliness: 3,
        socialHabits: 'SOCIAL',
        studyHabits: 'ANY',
        profileCompleted: true,
        roomPreferenceCompleted: true,
        finalLockCompleted: false,
    },
    {
        _id: studentIds[8],
        firstName: 'Dilini',
        lastName: 'Gunawardena',
        address: '11 Lotus Terrace, Battaramulla',
        email: 'dilini.g@university.lk',
        whatsApp: '+94771234509',
        gender: 'Female',
        age: 20,
        sleepSchedule: 'EARLY_BIRD',
        cleanliness: 5,
        socialHabits: 'QUIET',
        studyHabits: 'SOME_NOISE',
        profileCompleted: true,
        roomPreferenceCompleted: true,
        finalLockCompleted: false,
    },
    {
        _id: studentIds[9],
        firstName: 'Isuri',
        lastName: 'Bandara',
        address: '90 Queens Road, Anuradhapura',
        email: 'isuri.b@university.lk',
        whatsApp: '+94771234510',
        gender: 'Female',
        age: 23,
        sleepSchedule: 'NIGHT_OWL',
        cleanliness: 2,
        socialHabits: 'MODERATE',
        studyHabits: 'ANY',
        profileCompleted: true,
        roomPreferenceCompleted: true,
        finalLockCompleted: false,
    },
];

// ── Room preferences ──
const roomPreferences = [
    { studentId: studentIds[0], block: 'A', floor: '1', acType: 'AC', roomPosition: 'BALCONY', capacity: 2 },
    { studentId: studentIds[1], block: 'A', floor: '1', acType: 'AC', roomPosition: 'BALCONY', capacity: 2 },
    { studentId: studentIds[2], block: 'A', floor: '2', acType: 'NON_AC', roomPosition: 'MIDDLE', capacity: 2 },
    { studentId: studentIds[3], block: 'B', floor: '1', acType: 'NON_AC', roomPosition: 'MIDDLE', capacity: 2 },
    { studentId: studentIds[4], block: 'A', floor: '1', acType: 'AC', roomPosition: 'BALCONY', capacity: 2 },
    { studentId: studentIds[5], block: 'C', floor: '1', acType: 'AC', roomPosition: 'BALCONY', capacity: 2 },
    { studentId: studentIds[6], block: 'C', floor: '1', acType: 'AC', roomPosition: 'BALCONY', capacity: 2 },
    { studentId: studentIds[7], block: 'C', floor: '2', acType: 'NON_AC', roomPosition: 'MIDDLE', capacity: 2 },
    { studentId: studentIds[8], block: 'C', floor: '1', acType: 'AC', roomPosition: 'BALCONY', capacity: 2 },
    { studentId: studentIds[9], block: 'C', floor: '2', acType: 'NON_AC', roomPosition: 'MIDDLE', capacity: 2 },
];

// ── Rooms (8 rooms) ──
const rooms = [
    { roomNumber: 'A-101', block: 'A', floor: '1', acType: 'AC', roomPosition: 'BALCONY', capacity: 2, occupancyCount: 0, availabilityStatus: 'AVAILABLE', assignedStudents: [] },
    { roomNumber: 'A-102', block: 'A', floor: '1', acType: 'AC', roomPosition: 'MIDDLE', capacity: 2, occupancyCount: 0, availabilityStatus: 'AVAILABLE', assignedStudents: [] },
    { roomNumber: 'A-201', block: 'A', floor: '2', acType: 'NON_AC', roomPosition: 'MIDDLE', capacity: 2, occupancyCount: 0, availabilityStatus: 'AVAILABLE', assignedStudents: [] },
    { roomNumber: 'A-202', block: 'A', floor: '2', acType: 'NON_AC', roomPosition: 'BALCONY', capacity: 3, occupancyCount: 0, availabilityStatus: 'AVAILABLE', assignedStudents: [] },
    { roomNumber: 'B-101', block: 'B', floor: '1', acType: 'NON_AC', roomPosition: 'MIDDLE', capacity: 2, occupancyCount: 0, availabilityStatus: 'AVAILABLE', assignedStudents: [] },
    { roomNumber: 'B-102', block: 'B', floor: '1', acType: 'AC', roomPosition: 'BALCONY', capacity: 4, occupancyCount: 0, availabilityStatus: 'AVAILABLE', assignedStudents: [] },
    { roomNumber: 'C-101', block: 'C', floor: '1', acType: 'AC', roomPosition: 'BALCONY', capacity: 2, occupancyCount: 0, availabilityStatus: 'AVAILABLE', assignedStudents: [] },
    { roomNumber: 'C-201', block: 'C', floor: '2', acType: 'NON_AC', roomPosition: 'MIDDLE', capacity: 2, occupancyCount: 0, availabilityStatus: 'MAINTENANCE', assignedStudents: [] },
];

// ── Match requests (a few pending and one rejected) ──
const matchRequests = [
    {
        senderStudentId: studentIds[0],
        receiverStudentId: studentIds[1],
        compatibilityScore: 94,
        status: 'PENDING',
    },
    {
        senderStudentId: studentIds[5],
        receiverStudentId: studentIds[6],
        compatibilityScore: 88,
        status: 'PENDING',
    },
    {
        senderStudentId: studentIds[2],
        receiverStudentId: studentIds[3],
        compatibilityScore: 63,
        status: 'REJECTED',
        respondedAt: new Date('2026-03-07'),
    },
];

// ── Notifications ──
const notifications = [
    {
        studentId: studentIds[1],
        type: 'MATCH_REQUEST_RECEIVED',
        title: 'New Match Request',
        message: 'Ashan Perera sent you a roommate request (94% match).',
        isRead: false,
    },
    {
        studentId: studentIds[6],
        type: 'MATCH_REQUEST_RECEIVED',
        title: 'New Match Request',
        message: 'Sachini Wijesinghe sent you a roommate request (88% match).',
        isRead: false,
    },
    {
        studentId: studentIds[2],
        type: 'MATCH_REQUEST_REJECTED',
        title: 'Request Rejected',
        message: 'Tharindu Jayawardena declined your roommate request.',
        isRead: true,
    },
];

// ── Issue reports ──
const issueReports = [
    {
        studentId: studentIds[2],
        title: 'Leaking tap in bathroom',
        description: 'The hot water tap in the shared bathroom has been dripping continuously for two days.',
        category: 'WATER',
        priority: 'HIGH',
        status: 'SUBMITTED',
        roomNumber: 'A-201',
    },
    {
        studentId: studentIds[7],
        title: 'Broken window latch',
        description: 'The latch on the window nearest to the balcony does not close properly.',
        category: 'ROOM_CONDITION',
        priority: 'MEDIUM',
        status: 'IN_PROGRESS',
        adminComment: 'Maintenance team has been notified. Expected fix within 48 hours.',
        roomNumber: 'C-201',
    },
    {
        studentId: studentIds[4],
        title: 'Corridor light not working',
        description: 'The light in the Block A first-floor corridor has been off for a week.',
        category: 'ELECTRICITY',
        priority: 'LOW',
        status: 'RESOLVED',
        roomNumber: 'A-101',
    },
];

module.exports = {
    studentIds,
    students,
    roomPreferences,
    rooms,
    matchRequests,
    notifications,
    issueReports,
};
